name: Docker Image CI

on:
  push:
    branches: [ "main", "develop", "test" ]

jobs:
  copilot:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials for Staging
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TOOLS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TOOLS }}
          aws-region: ${{ secrets.AWS_REGION_TOOLS }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_STAGING_ARN }}
          role-duration-seconds: 1200
          role-session-name: StagingDeploymentSession

      - name: Install copilot
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          # download copilot
          curl -Lo copilot-linux https://github.com/aws/copilot-cli/releases/download/v1.27.0/copilot-linux && \
          # make copilot bin executable
          chmod +x copilot-linux && \
          # move to path
          mv copilot-linux $GITHUB_WORKSPACE/bin/copilot && \
          # add to PATH
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - run: copilot svc deploy --name webserver --env staging
        env:
          DOCKER_BUILDKIT: 1